In [1]:
import pandas as pd
import numpy as np

In [2]:
standpoint = pd.read_csv('BlackJackSimulation22.csv')

In [3]:
standpoint.head(20)

,Unnamed: 0,Dealer Show,Game Result,Player Hand,Player Hand Split,split flag
0,0,10,-1,19,0.0,False
1,1,3,-1,13,0.0,False
2,2,10,-1,13,0.0,False
3,3,3,-1,17,0.0,False
4,4,10,-1,16,0.0,False
5,5,5,-1,13,0.0,False
6,6,4,-1,17,0.0,False
7,7,10,-1,21,0.0,False
8,8,10,-1,9,0.0,False
9,9,8,-1,15,0.0,False
10,10,10,-1,18,0.0,False
11,11,6,-2,20,10.0,True
12,12,2,-1,14,0.0,False
13,13,10,-1,9,0.0,False
14,14,10,-1,14,0.0,False
15,15,2,-1,17,0.0,False
16,16,11,-1,19,0.0,False
17,17,10,-1,12,0.0,False
18,18,2,-1,15,0.0,False
19,19,6,-1,18,0.0,False

In [4]:
SplitTrue = standpoint[standpoint['split flag']==True]
SplitFalse = standpoint[standpoint['split flag']==False]

In [5]:
TRUE = SplitTrue[['Player Hand','Dealer Show','Game Result']]

In [6]:
FALSE = SplitFalse[['Player Hand','Dealer Show','Game Result']]

In [7]:
TRUE_Result = pd.DataFrame(TRUE.groupby([TRUE['Player Hand'],TRUE['Dealer Show']]).sum(), columns=['Game Result']).reset_index()
TRUE_Count = pd.DataFrame(TRUE.groupby([TRUE['Player Hand'],TRUE['Dealer Show']]).size(), columns=['Count']).reset_index()
df_output_T = pd.merge(TRUE_Result, TRUE_Count, how='inner',on=['Player Hand', 'Dealer Show']).sort_values(['Player Hand', 'Dealer Show'], ascending=[True, True])
df_output_T['Expectation'] = df_output_T['Game Result']/df_output_T['Count']

In [8]:
FALSE_Result = pd.DataFrame(FALSE.groupby([FALSE['Player Hand'],FALSE['Dealer Show']]).sum(), columns=['Game Result']).reset_index()
FALSE_Count = pd.DataFrame(FALSE.groupby([FALSE['Player Hand'],FALSE['Dealer Show']]).size(), columns=['Count']).reset_index()
df_output_F = pd.merge(FALSE_Result, FALSE_Count, how='inner',on=['Player Hand', 'Dealer Show']).sort_values(['Player Hand', 'Dealer Show'], ascending=[True, True])
df_output_F['Expectation'] = df_output_F['Game Result']/df_output_F['Count']

In [9]:
df_output_T.head(20)

    Player Hand  Dealer Show  Game Result  Count  Expectation
0             4            2         -822    411         -2.0
1             4            3         -932    466         -2.0
2             4            4         -852    426         -2.0
3             4            5         -962    481         -2.0
4             4            6         -910    455         -2.0
5             4            7         -886    443         -2.0
6             4            8         -884    442         -2.0
7             4            9         -864    432         -2.0
8             4           10        -3500   1750         -2.0
9             4           11         -942    471         -2.0
10            6            2         -876    438         -2.0
11            6            3         -724    362         -2.0
12            6            4         -890    445         -2.0
13            6            5         -930    465         -2.0
14            6            6         -914    457         -2.0
15            6            7         -870    435         -2.0
16            6            8         -926    463         -2.0
17            6            9         -920    460         -2.0
18            6           10        -3548   1774         -2.0
19            6           11         -860    430         -2.0

In [10]:
df_output_T.to_csv('output_True_22.csv')

In [11]:
df_output_F.head(20)

    Player Hand  Dealer Show  Game Result  Count  Expectation
0             5            2         -864    864         -1.0
1             5            3         -886    886         -1.0
2             5            4         -920    920         -1.0
3             5            5         -903    903         -1.0
4             5            6         -863    863         -1.0
5             5            7         -980    980         -1.0
6             5            8         -984    984         -1.0
7             5            9         -938    938         -1.0
8             5           10        -3581   3581         -1.0
9             5           11         -939    939         -1.0
10            6            2         -786    786         -1.0
11            6            3         -924    924         -1.0
12            6            4         -893    893         -1.0
13            6            5         -936    936         -1.0
14            6            6         -905    905         -1.0
15            6            7         -929    929         -1.0
16            6            8         -908    908         -1.0
17            6            9         -959    959         -1.0
18            6           10        -3655   3655         -1.0
19            6           11         -934    934         -1.0

In [12]:
df_output_F.to_csv('output_False_22.csv')